import {el,button,escapeHtml} from '../shared.js';
export function errorBox(){return el('p',{class:'notice aux-error',role:'alert',hidden:true});}
export function showError(node,error,t){const messages={PNG:['PNG를 만들지 못했습니다. 다시 시도해 주세요.','Could not create the PNG. Please try again.'],EMPTY:['입력값을 넣어 주세요.','Enter a value.'],LIMIT_500_BYTES:['QR 데이터는 UTF-8 500바이트까지입니다.','QR data is limited to 500 UTF-8 bytes.'],INVALID_UNICODE:['손상된 Unicode 문자가 있습니다.','The text contains invalid Unicode.'],HTTP_URL:['공백이나 계정정보 없는 http/https 주소를 입력하세요.','Enter an http/https URL without surrounding whitespace or credentials.'],INVALID_DECIMAL:['숫자는 0 이상, 소수점 6자리 이내로 입력하세요. 값이 너무 클 수도 있습니다.','Use a nonnegative number with up to 6 decimals, within the supported limit.'],ITEM_INVALID:['모든 품목의 이름과 0보다 큰 수량을 입력하세요.','Each item needs a name and a positive quantity.'],ITEM_LIMIT:['품목은 1~100개까지입니다.','Use 1–100 items.'],TOTAL_LIMIT:['지원하는 문서 금액 한도를 초과했습니다.','The document exceeds the supported total.'],ROOM_LIMIT:['방은 1~20개까지입니다.','Use 1–20 rooms.'],ROOM_NAME:['모든 방에 이름을 입력하세요.','Name every room.'],NUMBER:['숫자는 0 이상, 소수점 6자리 이내로 입력하세요.','Use a nonnegative decimal with up to 6 places.'],RANGE:['입력값이 지원 범위를 벗어났습니다.','A value is outside the supported range.'],COST_LIMIT:['예상 비용은 1조 이하만 지원합니다.','Estimated cost is limited to 1 trillion currency units.'],PACK_LIMIT:['계산된 포장 수가 너무 큽니다.','The calculated package count is too large.'],COATS:['도포 횟수는 1~10의 정수입니다.','Coats must be an integer from 1 to 10.'],HOURS_EQUAL:['시작과 종료 시각은 달라야 합니다.','Availability start and end must differ.'],LOCAL_RANGE:['1970~2100년의 유효한 날짜와 시각을 입력하세요.','Enter a valid date and time between 1970 and 2100.'],LOCAL_FORMAT:['날짜와 시각을 입력하세요.','Enter a date and time.'],CLOCK:['유효한 시각을 입력하세요.','Enter a valid time.'],ZONE_LIMIT:['시간대는 1~6개까지입니다.','Use 1–6 time zones.']};const pair=messages[error.message];node.textContent=pair?t(...pair):t('QR을 처리하지 못했습니다. 입력값을 확인하고 다시 시도해 주세요.','Could not process the QR code. Check the input and try again.');node.hidden=false;}
export function toolbar(...nodes){return el('div',{class:'toolbar aux-toolbar'},...nodes);}
export function printDocument(html,title,t){
 const frame=el('iframe',{class:'aux-print-frame',title:t('인쇄 문서','Print document')});
 frame.onload=()=>{setTimeout(()=>{if(!frame.isConnected)return;frame.contentWindow.focus();frame.contentWindow.print();},100);};
 frame.srcdoc=`<!doctype html><html><head><meta charset="utf-8"><title>${escapeHtml(title)}</title><style>body{font:14px system-ui,sans-serif;color:#162322;margin:32px}h1{font-size:28px}h2{font-size:18px}.meta{white-space:pre-wrap;display:flex;gap:40px}.meta>div{flex:1}table{width:100%;border-collapse:collapse;margin:24px 0}th,td{text-align:left;padding:10px;border-bottom:1px solid #ccd7d5;overflow-wrap:anywhere}th{background:#edf4f2}.right{text-align:right}.note{white-space:pre-wrap;overflow-wrap:anywhere;color:#4d605d;font-size:12px}tr{break-inside:avoid}thead{display:table-header-group}@page{size:A4;margin:18mm}@media print{body{margin:0}}</style></head><body>${html}</body></html>`;
 document.body.append(frame);
 const timer=setTimeout(()=>frame.remove(),120000);
 return ()=>{clearTimeout(timer);frame.remove();};
}
export function clearButton(t,handler){return button(t('초기화','Reset'),handler,true);}
