import {el,field,button,select,download,tFor,setDirty} from '../shared.js';
import {encodeQR,qrSvg} from '../lib/qr-engine.js';
import {errorBox,showError,toolbar,printDocument} from './auxiliary-ui.js';
import {toolMetrics} from '../measurement.js';
export function mount(root,{lang='ko',t=tFor(lang),toast=()=>{}}={}){
 const metrics=toolMetrics('qr');let current=null,revision=0,alive=true;const cleanups=[];
 const mode=select([['url',t('웹 주소','Web URL')],['text',t('텍스트','Text')]],'url');
 const input=el('textarea',{rows:4,maxlength:500,placeholder:'https://example.com',value:'https://example.com','aria-label':t('QR에 넣을 데이터','QR data')});
 const size=select([['256','256 px'],['512','512 px'],['1024','1024 px']],'512');
 const counter=el('small',{class:'aux-muted'}),error=errorBox();
 const preview=el('div',{class:'aux-qr','aria-live':'polite'}),data=el('p',{class:'aux-qr-data aux-muted'});
 const svgButton=button(t('SVG 저장','Save SVG'),()=>{const measurement=metrics.begin('qr_svg');try{const blob=new Blob([current.svg],{type:'image/svg+xml'});metrics.success(measurement);metrics.artifact(measurement);metrics.download('qr_svg',measurement);download(blob,'qr-code.svg');}catch(e){metrics.fail(measurement);showError(error,e,t);}});
 const pngButton=button(t('PNG 저장','Save PNG'),()=>{const own=revision,snapshot=current,measurement=metrics.begin('qr_png');try{const n=snapshot.matrix.length+8,scale=Math.ceil(Number(size.value)/n),canvas=document.createElement('canvas');canvas.width=canvas.height=n*scale;const ctx=canvas.getContext('2d');ctx.fillStyle='#fff';ctx.fillRect(0,0,canvas.width,canvas.height);ctx.fillStyle='#000';snapshot.matrix.forEach((row,y)=>row.forEach((dark,x)=>{if(dark)ctx.fillRect((x+4)*scale,(y+4)*scale,scale,scale);}));canvas.toBlob(blob=>{if(!alive||own!==revision||current!==snapshot)return;if(!blob){metrics.fail(measurement);showError(error,new Error('PNG'),t);return;}metrics.success(measurement);metrics.artifact(measurement);metrics.download('qr_png',measurement);download(blob,'qr-code.png');},'image/png');}catch(e){metrics.fail(measurement);showError(error,e,t);}});
 const print=button(t('인쇄 / PDF로 저장','Print / Save as PDF'),()=>{metrics.print('qr_print');cleanups.push(printDocument(`<h1>QR</h1><div style="width:50mm;height:50mm">${current.svg.replace(/width="\d+" height="\d+"/,'width="100%" height="100%"')}</div><p>${t('실제 크기로 인쇄 후 휴대전화로 스캔을 확인하세요.','Print at actual size and test with your phone.')}</p>`,'QR',t));},true);
 function resetResult(){current=null;preview.replaceChildren(el('p',{class:'aux-muted'},t('생성하면 여기에 QR이 표시됩니다.','Your generated QR will appear here.')));data.textContent='';svgButton.disabled=pngButton.disabled=print.disabled=true;}
 function update(){revision++;metrics.cancelAll();counter.textContent=`${new TextEncoder().encode(input.value).length} / 500 ${t('UTF-8 바이트','UTF-8 bytes')}`;resetResult();error.hidden=true;setDirty();}
 function generate(){const measurement=metrics.begin('qr_encode');error.hidden=true;try{const matrix=encodeQR(input.value,mode.value),svg=qrSvg(matrix,Number(size.value));current={matrix,svg};metrics.success(measurement);metrics.artifact(measurement);preview.innerHTML=svg;preview.querySelector('svg').setAttribute('role','img');preview.querySelector('svg').setAttribute('aria-label',t('생성한 정적 QR 코드','Generated static QR code'));data.textContent=input.value;svgButton.disabled=pngButton.disabled=print.disabled=false;toast(t('QR을 생성했습니다. 저장 후 스캔을 확인하세요.','QR generated. Verify it by scanning after saving.'));}catch(e){metrics.fail(measurement,'validation');resetResult();showError(error,e,t);}}
 input.addEventListener('input',update);mode.addEventListener('change',update);size.addEventListener('change',update);
 root.replaceChildren(el('div',{class:'aux-tool'},el('div',{class:'notice'},t('정적 QR 1개를 로컬에서 만듭니다. 주소를 방문하거나 단축·추적하지 않습니다. 데이터 500바이트 · 여백 4모듈 · 오류 복원 M','Create one static QR locally. URLs are never visited, shortened, or tracked. 500-byte limit · 4-module quiet zone · M error correction')),el('div',{class:'grid-2'},el('section',{class:'panel'},field(t('내용 종류','Content type'),mode),field(t('데이터','Data'),input),counter,field(t('출력 크기','Output size'),size,t('PNG는 선명한 정수 배율로 올림됩니다.','PNG dimensions are rounded up to whole-module pixels.')),toolbar(button(t('QR 생성','Generate QR'),generate),button(t('비우기','Clear'),()=>{input.value='';update();input.focus();},true)),error),el('section',{class:'panel'},preview,data,toolbar(pngButton,svgButton,print)))));
 update();setDirty(false);return()=>{metrics.dispose();alive=false;revision++;current=null;cleanups.forEach(fn=>fn());};
}
