import {el,field,button,download,bytes,select,inputNumber,setDirty,isMobile,nextFrame} from '../shared.js';
import {outputNames,validateSpec} from '../lib/image-core.js';
import {decodeImage,renderImage} from '../lib/image-browser.js';
import {toolMetrics} from '../measurement.js';
export function mount(root,{t,toast}){
 const metrics=toolMetrics('images');
 let files=[],specs=[{id:'s1',name:'standard',width:1200,height:1200,mode:'contain',format:'image/jpeg',quality:.85,targetKB:0,background:'#ffffff',upscale:false}],results=[],failures=[],busy=false,cancel=false,disposed=false,urls=[],run=0,outputVersion=0,previewToken=0,omitted=[],clearAfter=false;
 // Settings survive Clear all, so keep their dirty state separate from selected files.
 let settingsDirty=false;
 function updateDirty(){setDirty(settingsDirty||!!files.length);}
 function markSettingsDirty(){settingsDirty=true;updateDirty();}
 const mobile=isMobile(),maxFiles=mobile?10:20,maxBytes=(mobile?40:100)*1048576,maxPixels=(mobile?12:24)*1000000,maxOutput=(mobile?60:200)*1048576;
 const status=el('p',{class:'notice',role:'status','aria-live':'polite'},t('파일을 선택하면 이 기기에서 검사합니다','Choose files to validate on this device'));
 const input=el('input',{type:'file',multiple:true,accept:'image/jpeg,image/png,image/webp','aria-label':t('사진 선택','Choose images')});
 const list=el('div',{class:'file-list'}),presets=el('div',{class:'preset-list'}),out=el('div'),preview=el('div',{class:'image-preview'}),names=el('details',{},el('summary',{},t('최종 파일명 미리보기','Final filename preview')));
 const prefix=el('input',{type:'text',value:'',maxLength:50,placeholder:'project'}),original=el('input',{type:'checkbox',checked:true});
 const runButton=button(t('일괄 변환','Convert batch'),()=>process(false));const retry=button(t('실패한 항목 재시도','Retry failed items'),()=>process(true),true);retry.hidden=true;
 const cancelButton=button(t('취소','Cancel'),()=>{metrics.cancelAction('image_batch','user_cancel');cancel=true;status.textContent=t('현재 이미지 처리 후 중단합니다','Stopping after the current image')},true);cancelButton.disabled=true;
 const zipButton=button(t('성공 파일 ZIP 저장','Download successful files as ZIP'),async()=>{zipButton.disabled=true;const zipVersion=outputVersion,measurement=metrics.begin('image_zip');try{const zip=new window.JSZip();results.forEach(r=>zip.file(r.name,r.blob));zip.file('_manifest.txt',`LOCAL / 11\n${results.length} result(s); ${failures.length} failed; ${omitted.length} unprocessed\n`+results.map(r=>`${r.name}\t${r.dw}x${r.dh}\t${r.blob.size} bytes\t${r.met?'OK':'TARGET SIZE NOT MET'}`).join('\n')+'\nFAILED\n'+failures.map(f=>`${f.name}: ${f.error}`).join('\n')+'\nUNPROCESSED\n'+omitted.map(f=>f.name).join('\n'));const blob=await zip.generateAsync({type:'blob',compression:'STORE'});if(disposed||zipVersion!==outputVersion)return;metrics.success(measurement);metrics.artifact(measurement);metrics.download('image_zip',measurement);download(blob,'images.zip');toast(t('ZIP을 생성했습니다','ZIP created'));}catch(e){metrics.fail(measurement);status.textContent=e.message;}finally{zipButton.disabled=false;} });zipButton.hidden=true;
 function updateNames(){names.replaceChildren(el('summary',{},t('최종 파일명 미리보기','Final filename preview')),el('pre',{},outputNames(files,specs,prefix.value,original.checked).map(n=>n.name).join('\n')||'—'));}
 function revoke(retire=true){if(retire)metrics.cancelAction('image_preview');previewToken++;urls.forEach(u=>URL.revokeObjectURL(u));urls=[];preview.replaceChildren();}
 function renderFiles(){list.replaceChildren(...files.map((f,i)=>el('div',{class:'file-row'},el('span',{},`${i+1}. ${f.name}`),el('small',{},bytes(f.size)),button(t('제외','Remove'),()=>{if(busy)return;outputVersion++;results=[];failures=[];omitted=[];out.replaceChildren();zipButton.hidden=true;retry.hidden=true;files.splice(i,1);revoke();renderFiles();updateNames();},true))));updateNames();}
 input.addEventListener('change',()=>{if(busy)return;const picked=Array.from(input.files||[]),measurement=picked.length?metrics.begin('validate_images'):null;if(picked.length>maxFiles||picked.reduce((n,f)=>n+f.size,0)>maxBytes){status.textContent=t(`한도: ${maxFiles}장 / ${maxBytes/1048576} MiB. 나누어 선택하세요`,`Limit: ${maxFiles} images / ${maxBytes/1048576} MiB. Split the batch.`);input.value='';metrics.fail(measurement,'validation');return;}metrics.success(measurement);files=picked;outputVersion++;results=[];failures=[];omitted=[];out.replaceChildren();zipButton.hidden=true;retry.hidden=true;revoke();renderFiles();updateDirty();status.textContent=t(`${files.length}장 선택. 실행 전 형식·픽셀을 검사합니다`,`${files.length} selected. Format and pixel dimensions checked before processing.`);});
 function renderPresets(){presets.replaceChildren(...specs.map((s,i)=>{const name=el('input',{value:s.name,maxLength:30}),w=inputNumber(s.width,16,4096),h=inputNumber(s.height,16,4096),format=select([['image/jpeg','JPEG'],['image/png','PNG'],['image/webp','WebP']],s.format),mode=select([['contain',t('비율 유지 · 안쪽 맞춤','Contain · preserve ratio')],['cover',t('중앙 자르기','Center crop')]],s.mode),quality=inputNumber(Math.round(s.quality*100),30,100),target=inputNumber(s.targetKB,0,204800),up=el('input',{type:'checkbox',checked:s.upscale}),bg=el('input',{type:'color',value:s.background});function sync(){markSettingsDirty();Object.assign(s,{name:name.value,width:+w.value,height:+h.value,format:format.value,mode:mode.value,quality:+quality.value/100,targetKB:+target.value,upscale:up.checked,background:bg.value});quality.disabled=format.value==='image/png';target.disabled=format.value==='image/png';updateNames();revoke();}for(const e of [name,w,h,format,mode,quality,target,up,bg]){e.addEventListener('input',markSettingsDirty);e.addEventListener('change',sync);}quality.disabled=s.format==='image/png';target.disabled=s.format==='image/png';return el('section',{class:'panel preset'},el('div',{class:'section-heading'},el('h3',{},`${t('규격','Preset')} ${i+1}`),specs.length>1?button(t('삭제','Remove'),()=>{if(busy)return;specs.splice(i,1);markSettingsDirty();renderPresets();updateNames();},true):null),el('div',{class:'grid-3'},field(t('규격 이름','Preset name'),name),field(t('너비 px','Width px'),w),field(t('높이 px','Height px'),h),field(t('출력 형식','Output format'),format),field(t('맞춤 방식','Fit'),mode),field(t('품질 %','Quality %'),quality),field(t('목표 KiB · 0은 해제','Target KiB · 0 disables'),target),field(t('JPEG 배경색','JPEG background'),bg),field(t('확대 허용','Allow upscaling'),up)));}));add.disabled=specs.length>=3;}
 const add=button(t('+ 출력 규격 추가','+ Add output preset'),()=>{if(busy||specs.length>=3)return;specs.push({...specs[0],id:crypto.randomUUID(),name:`preset${specs.length+1}`});markSettingsDirty();renderPresets();updateNames();},true);
 const previewButton=button(t('첫 사진 변환 미리보기','Preview first image'),async()=>{if(!files.length)return;previewButton.disabled=true;const measurement=metrics.begin('image_preview'),previewVersion=++previewToken,previewSpec=structuredClone(specs[0]);try{specs.forEach(validateSpec);const decoded=await decodeImage(files[0],maxPixels);try{const r=await renderImage(decoded.bitmap,previewSpec);if(disposed||previewVersion!==previewToken)return;revoke(false);metrics.success(measurement);metrics.artifact(measurement);const url=URL.createObjectURL(r.blob);urls.push(url);preview.append(el('img',{src:url,alt:t('첫 규격의 실제 변환 미리보기','Actual converted first preset')}),el('p',{},`${r.dw} × ${r.dh}px · ${bytes(r.blob.size)} · ${r.cropped?t('중앙 잘림','center cropped'):t('전체 보이기','full image')} ${r.met?'':t('· 목표 용량 미달','· target size not met')}`));}finally{decoded.bitmap.close();}}catch(e){metrics.fail(measurement);status.textContent=e.message;}finally{previewButton.disabled=false;}},true);
 function renderResults(){const table=el('table',{class:'result-table'},el('thead',{},el('tr',{},[t('출력','Output'),t('크기','Dimensions'),t('용량 / 결과','Size / status'),''].map(v=>el('th',{scope:'col'},v))))),body=el('tbody');results.forEach(r=>body.append(el('tr',{},el('td',{},r.name),el('td',{},`${r.dw}×${r.dh}`),el('td',{},`${bytes(r.blob.size)} · ${r.met?t('완료','Done'):t('목표 용량 미달','Target not met')}`),el('td',{},button(t('저장','Save'),()=>{metrics.download('image_batch');download(r.blob,r.name.split('/').pop());},true)))));table.append(body);out.replaceChildren(el('div',{class:'table-scroll'},table),...failures.map(f=>el('p',{class:'notice warning'},`${f.file?.name||files[f.fileIndex]?.name||''} / ${f.specId}: ${f.error}`)));zipButton.hidden=!results.length;retry.hidden=!failures.length;}
 function clearAll(){
   metrics.cancelAll('user_cancel');
   if(busy){cancel=true;clearAfter=true;return;}
   outputVersion++;files=[];results=[];failures=[];omitted=[];input.value='';list.replaceChildren();out.replaceChildren();revoke();zipButton.hidden=true;retry.hidden=true;updateNames();updateDirty();status.textContent=t('작업 메모리를 지웠습니다','Workspace memory cleared');
 }
 async function process(onlyFailed){
   if(busy||!files.length)return;
   const measurement=metrics.begin('image_batch');
   try{if(!onlyFailed)specs.forEach(validateSpec);}catch(e){metrics.fail(measurement,'validation');status.textContent=e.message;return;}
   let tasks=onlyFailed?failures.map(f=>({...f})):outputNames(files,specs,prefix.value,original.checked).map(task=>({...task,file:files[task.fileIndex],spec:structuredClone(specs.find(s=>s.id===task.specId))}));
   busy=true;cancel=false;clearAfter=false;run++;outputVersion++;const current=run;
   runButton.disabled=true;previewButton.disabled=true;input.disabled=true;cancelButton.disabled=false;zipButton.disabled=true;
   presets.querySelectorAll('input,select,button').forEach(e=>e.disabled=true);
   prefix.disabled=true;original.disabled=true;add.disabled=true;retry.disabled=true;loadSettings.disabled=true;revoke();
   // A retry owns only failed tasks; earlier unprocessed tasks still belong to this batch.
   if(!onlyFailed){results=[];omitted=[];}failures=[];
   let size=results.reduce((n,r)=>n+r.blob.size,0),stopped=omitted.length>0;
   for(let i=0;i<tasks.length;i++){
     if(cancel||disposed||current!==run){stopped=true;omitted.push(...tasks.slice(i));break;}
     const task=tasks[i],spec=task.spec;status.textContent=t(`처리 중 ${i+1}/${tasks.length}`,`Processing ${i+1}/${tasks.length}`);let decoded;
     try{
       decoded=await decodeImage(task.file,maxPixels);const result=await renderImage(decoded.bitmap,spec);
       if(disposed||current!==run)break;
       if(size+result.blob.size>maxOutput){failures.push({...task,error:t('출력 메모리 예산 초과. 묶음을 나누세요','Output memory budget exceeded. Split the batch.')});stopped=true;omitted.push(...tasks.slice(i+1));break;}
       size+=result.blob.size;results.push({...task,...result});
     }catch(e){failures.push({...task,error:e.message});}finally{decoded?.bitmap.close();}
     await nextFrame();
   }
   busy=false;if(disposed)return;
   if(cancel){metrics.cancel(measurement);if(results.length&&!clearAfter)metrics.artifact(measurement);}else if(!results.length&&failures.length)metrics.fail(measurement);else{metrics.success(measurement,stopped||failures.length?'partial':'complete');metrics.artifact(measurement);}
   input.disabled=false;runButton.disabled=false;previewButton.disabled=false;cancelButton.disabled=true;prefix.disabled=false;original.disabled=false;retry.disabled=false;loadSettings.disabled=false;zipButton.disabled=false;
   renderPresets();renderResults();status.textContent=t(`${stopped?'중단 / 부분 완료':'처리 완료'} · 저장 가능 ${results.length} · 실패 ${failures.length} · 미처리 ${omitted.length}`,`${stopped?'Stopped / partial':'Finished'} · ${results.length} available · ${failures.length} failed · ${omitted.length} unprocessed`);
   if(clearAfter){clearAfter=false;clearAll();}
 }
 const saveSettings=button(t('설정 JSON 저장','Save settings JSON'),()=>{const measurement=metrics.begin('settings_export'),blob=new Blob([JSON.stringify({version:1,specs:specs.map(({id,name,...s})=>s)},null,2)],{type:'application/json'});metrics.success(measurement);metrics.artifact(measurement);metrics.download('settings_export',measurement);download(blob,'image-settings.json');},true);
 const loadSettings=el('input',{type:'file',accept:'.json','aria-label':t('설정 JSON 불러오기','Load settings JSON')});loadSettings.addEventListener('change',async()=>{if(busy)return;const settingsVersion=previewToken,settingsRun=run;try{const f=loadSettings.files[0];if(!f)return;if(f.size>16384)throw new Error('Settings too large');const raw=await f.text();if(disposed||busy||settingsRun!==run||settingsVersion!==previewToken)return;const data=JSON.parse(raw);if(data.version!==1||!Array.isArray(data.specs)||data.specs.length<1||data.specs.length>3)throw new Error('Invalid settings');specs=data.specs.map((s,i)=>validateSpec({...s,id:crypto.randomUUID(),name:`preset${i+1}`}));markSettingsDirty();revoke();renderPresets();updateNames();toast(t('내용 없는 규격 설정을 불러왔습니다','Content-free presets loaded'));}catch(e){status.textContent=e.message;}finally{loadSettings.value='';}});
 root.append(el('div',{class:'notice privacy'},t('원본 보존 · 파일 전송 없음 · EXIF/GPS 제거 · 새로고침하면 작업 내용이 사라집니다','Originals preserved · No file uploads · EXIF/GPS removed · Refresh clears this workspace')),el('section',{class:'panel'},el('div',{class:'section-heading'},el('h2',{},t('01 파일 선택','01 Choose files')),el('span',{class:'badge'},`${maxFiles} / ${maxBytes/1048576} MiB / ${maxPixels/1000000} MP`)),el('div',{class:'dropzone'},el('strong',{},t('JPG · PNG · 정적 WebP','JPG · PNG · static WebP')),input,el('small',{},t('HEIC, RAW, SVG, 애니메이션은 제외합니다','HEIC, RAW, SVG and animation are unsupported'))),list),el('section',{},el('div',{class:'section-heading'},el('h2',{},t('02 출력 규격','02 Output presets')),add),presets,el('p',{class:'notice'},t('JPEG는 투명 배경을 선택한 색으로 채웁니다. 확대를 끄면 원본보다 큰 치수를 만들지 않습니다. PNG에는 손실 품질·목표 용량을 적용하지 않습니다','JPEG flattens transparency onto the chosen color. With upscaling off, output never exceeds original dimensions. PNG ignores lossy quality and target size.'))),el('section',{class:'panel'},el('div',{class:'grid-2'},field(t('파일명 접두어','Filename prefix'),prefix),field(t('원래 파일명 포함','Include original filename'),original)),names,el('div',{class:'toolbar'},previewButton,saveSettings,field(t('설정 JSON 불러오기','Load settings JSON'),loadSettings)),preview),status,el('div',{class:'toolbar sticky-actions'},runButton,cancelButton,retry,zipButton,button(t('전체 지우기','Clear all'),clearAll,true)),out);
 prefix.addEventListener('input',()=>{markSettingsDirty();updateNames();});original.addEventListener('change',()=>{markSettingsDirty();updateNames();});renderPresets();return()=>{metrics.dispose();disposed=true;cancel=true;run++;files=[];results=[];revoke();};
}
