import {el,field,button,select,escapeHtml,download,tFor,setDirty} from '../shared.js';
import {calculateQuantity,quantityCsv} from '../lib/quantity-engine.js';
import {errorBox,showError,toolbar,printDocument} from './auxiliary-ui.js';
import {toolMetrics} from '../measurement.js';
export function mount(root,{lang='ko',t=tFor(lang),toast=()=>{}}={}){
 const metrics=toolMetrics('quantity');let result=null,html='';const cleanups=[],error=errorBox(),rooms=el('div',{class:'aux-rows'}),preview=el('section',{class:'panel','aria-live':'polite'});
 const type=select([['tile',t('타일 / 바닥재','Tile / flooring')],['paint',t('도료','Paint')]],'tile'),unit=select([['m2','m²'],['ft2','ft²'],['pyeong',t('평 (400/121 m²)','Pyeong (400/121 m²)')]],'m2');
 const coverage=el('input',{type:'number',min:0.000001,max:1000000,step:'any',value:1.6}),waste=el('input',{type:'number',min:0,max:100,step:'any',value:10}),coats=el('input',{type:'number',min:1,max:10,step:1,value:1,disabled:true}),price=el('input',{type:'number',min:0,max:1000000000,step:'any',value:0});
 const csv=button(t('CSV 저장','Save CSV'),()=>{const measurement=metrics.begin('quantity_csv');try{const blob=new Blob([quantityCsv(result)],{type:'text/csv;charset=utf-8'});metrics.success(measurement);metrics.artifact(measurement);metrics.download('quantity_csv',measurement);download(blob,'material-quantity.csv');}catch(e){metrics.fail(measurement);showError(error,e,t);}},true);
 const print=button(t('인쇄 / PDF로 저장','Print / Save as PDF'),()=>{metrics.print('quantity_print');cleanups.push(printDocument(html,t('자재 수량 계산','Material quantity'),t));},true);csv.disabled=print.disabled=true;
 const fmt=n=>new Intl.NumberFormat(lang==='en'?'en-US':'ko-KR',{maximumFractionDigits:6}).format(n);
 function dirty(){result=null;csv.disabled=print.disabled=true;preview.replaceChildren(el('p',{class:'aux-muted'},t('입력 후 계산하면 수량과 계산 근거가 표시됩니다.','Calculate to see quantities and assumptions.')));error.hidden=true;setDirty();}
 const add=button(t('+ 방 추가','+ Add room'),()=>{addRoom();dirty();},true);
 function addRoom(name='',area=''){if(rooms.children.length>=20)return;const row=el('div',{class:'aux-room-row'},field(t('방 / 구역 이름','Room / area name'),el('input',{value:name,maxlength:100,'data-key':'name'})),field(t('면적 (선택한 단위)','Area (selected unit)'),el('input',{type:'number',value:area,min:0.000001,max:1000000,step:'any','data-key':'area'})),button(t('삭제','Remove'),()=>{row.remove();add.disabled=false;dirty();},true));rooms.append(row);add.disabled=rooms.children.length>=20;}
 function calculate(track=true){const measurement=track===false?null:metrics.begin('quantity_calculate');try{error.hidden=true;
  // Only an omitted optional price means zero; malformed number input remains an error.
  if(price.validity?.badInput)throw new Error('NUMBER');
  const items=[...rooms.children].map(r=>Object.fromEntries([...r.querySelectorAll('[data-key]')].map(x=>[x.dataset.key,x.value])));result=calculateQuantity(items,{type:type.value,unit:unit.value,coverage:coverage.value,waste:waste.value,coats:coats.value,price:price.value.trim()||'0'});const u=unit.options[unit.selectedIndex].text;
  html=`<h1>${t('자재 수량 계산','Material quantity')}</h1><p>${type.options[type.selectedIndex].text} · ${t('동일 품목 기준','One shared material')}</p><table><thead><tr><th>${t('방 / 구역','Room / area')}</th><th>${t('면적','Area')} (${escapeHtml(u)})</th></tr></thead><tbody>${result.details.map(r=>`<tr><td>${escapeHtml(r.name)}</td><td>${fmt(r.area)}</td></tr>`).join('')}</tbody></table><p>${t('총면적','Total area')}: ${fmt(result.totalArea)} ${escapeHtml(u)} (${fmt(result.totalM2)} m²)</p><p>${t('계산식','Formula')}: ${fmt(result.totalArea)} × ${result.layers} × (1 + ${result.loss}/100) ÷ ${escapeHtml(coverage.value)} = ${fmt(result.rawPacks)}</p><p class="aux-total">${t('올림 후 주문 수량','Order after rounding up')}: ${result.packs} ${t('포장','packs')}</p><p>${t('필요 커버리지','Required coverage')}: ${fmt(result.neededArea)} ${escapeHtml(u)}</p><p>${t('예상 비용 (입력 단가의 통화)','Estimated cost (currency of entered price)')}: ${fmt(result.estimatedCost)}</p><p class="note">${t('같은 품목의 모든 면적을 합산한 뒤 손실률과 도포 횟수를 적용하고 마지막에 한 번 올림합니다. 도료 커버리지는 포장당 1회 도포 기준입니다. 구조·하중·전기·가스·안전 설계나 실측 결과가 아닙니다. 제조사 규격과 실제 현장 치수를 확인하세요.','Areas for one material are summed before waste, coats, and final package rounding. Paint coverage is per package for one coat. This is not a structural, load, electrical, gas, or safety design, nor a measurement. Verify manufacturer coverage and actual site dimensions.')}</p>`;
  preview.innerHTML=html;csv.disabled=print.disabled=false;metrics.success(measurement);metrics.artifact(measurement);toast(t('주문 수량을 계산했습니다.','Order quantity calculated.'));
 }catch(e){metrics.fail(measurement,'validation');result=null;csv.disabled=print.disabled=true;showError(error,e,t);}}
 const settings=el('section',{class:'panel'},el('div',{class:'grid-2'},field(t('계산 유형','Material type'),type),field(t('모든 면적·커버리지의 단위','Unit for ALL areas and coverage'),unit,t('단위를 바꾸면 기존 숫자도 새 단위로 해석합니다.','Changing units reinterprets existing numbers.'))),rooms,toolbar(add),el('div',{class:'grid-2'},field(t('포장당 커버리지 (선택한 단위)','Coverage per pack (selected unit)'),coverage),field(t('손실률 (%)','Waste (%)'),waste),field(t('도포 횟수 (도료만)','Coats (paint only)'),coats),field(t('포장당 단가 (선택)','Price per pack (optional)'),price)),toolbar(button(t('수량 계산','Calculate quantity'),calculate),csv,print),error);
 settings.addEventListener('input',dirty);settings.addEventListener('change',()=>{coats.disabled=type.value!=='paint';dirty();});
 root.replaceChildren(el('div',{class:'aux-tool'},el('div',{class:'notice'},t('한 품목 · 최대 20구역. 제조사 커버리지를 직접 입력하세요. 방마다 포장 수를 먼저 올림하지 않습니다. CSV 수식 접두문자 완화는 실험 기능이며 일부 방 이름 값에 작은따옴표를 추가합니다. Excel·LibreOffice 열기/재저장 검증 전이며 모든 환경의 수식 실행 방지를 보장하지 않습니다. 신뢰할 수 없는 값은 텍스트 열로 가져오세요.','One material, up to 20 areas. Enter manufacturer coverage. Package counts are rounded only after aggregation. CSV formula-prefix mitigation is experimental and changes some room names by adding an apostrophe. Excel/LibreOffice open–resave behavior has not been verified; formula execution prevention is not guaranteed. Import untrusted names as text columns.')),settings,preview));addRoom(t('방 1','Room 1'),'10');addRoom(t('방 2','Room 2'),'12');calculate(false);setDirty(false);return()=>{metrics.dispose();cleanups.forEach(fn=>fn());};
}
